// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9XmiwqRCPlK509cwaWDDBSmU4Crh9yvs',
    appId: '1:869970129570:web:04f511086de80fcc6bddfb',
    messagingSenderId: '869970129570',
    projectId: 'habit-tracker-eaf6b',
    authDomain: 'habit-tracker-eaf6b.firebaseapp.com',
    storageBucket: 'habit-tracker-eaf6b.appspot.com',
    measurementId: 'G-G94N6SY481',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALU4wgu-W9XIEY8NgS9pKdXGm6LxDcTd0',
    appId: '1:869970129570:android:617a386829663e886bddfb',
    messagingSenderId: '869970129570',
    projectId: 'habit-tracker-eaf6b',
    storageBucket: 'habit-tracker-eaf6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQTfvfEUWSDeorGsiYbRqnegYhU17m2ag',
    appId: '1:869970129570:ios:901a01b98156ebb06bddfb',
    messagingSenderId: '869970129570',
    projectId: 'habit-tracker-eaf6b',
    storageBucket: 'habit-tracker-eaf6b.appspot.com',
    iosBundleId: 'com.example.habitTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQTfvfEUWSDeorGsiYbRqnegYhU17m2ag',
    appId: '1:869970129570:ios:901a01b98156ebb06bddfb',
    messagingSenderId: '869970129570',
    projectId: 'habit-tracker-eaf6b',
    storageBucket: 'habit-tracker-eaf6b.appspot.com',
    iosBundleId: 'com.example.habitTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9XmiwqRCPlK509cwaWDDBSmU4Crh9yvs',
    appId: '1:869970129570:web:e9874ded08d4d19d6bddfb',
    messagingSenderId: '869970129570',
    projectId: 'habit-tracker-eaf6b',
    authDomain: 'habit-tracker-eaf6b.firebaseapp.com',
    storageBucket: 'habit-tracker-eaf6b.appspot.com',
    measurementId: 'G-9G9BM0BERB',
  );
}
